cd ~/enrico_ws/reconstructionEvaluator/output/KITTI/00_mono && ~/enrico_ws/reconstructionEvaluator/reconstructionEvaluator ~/enrico_ws/reconstructionEvaluator/config/kitti00_mono.config >> stdout &
#cd ~/enrico_ws/reconstructionEvaluator/output/KITTI/01 && ~/enrico_ws/reconstructionEvaluator/reconstructionEvaluator ~/enrico_ws/reconstructionEvaluator/config/kitti01_mono.config >> stdout &
cd ~/enrico_ws/reconstructionEvaluator/output/KITTI/02_mono && ~/enrico_ws/reconstructionEvaluator/reconstructionEvaluator ~/enrico_ws/reconstructionEvaluator/config/kitti02_mono.config >> stdout &
#cd ~/enrico_ws/reconstructionEvaluator/output/KITTI/03 && ~/enrico_ws/reconstructionEvaluator/reconstructionEvaluator ~/enrico_ws/reconstructionEvaluator/config/kitti03_mono.config >> stdout &
cd ~/enrico_ws/reconstructionEvaluator/output/KITTI/04_mono && ~/enrico_ws/reconstructionEvaluator/reconstructionEvaluator ~/enrico_ws/reconstructionEvaluator/config/kitti04_mono.config >> stdout &
cd ~/enrico_ws/reconstructionEvaluator/output/KITTI/05_mono && ~/enrico_ws/reconstructionEvaluator/reconstructionEvaluator ~/enrico_ws/reconstructionEvaluator/config/kitti05_mono.config >> stdout &
cd ~/enrico_ws/reconstructionEvaluator/output/KITTI/06_mono && ~/enrico_ws/reconstructionEvaluator/reconstructionEvaluator ~/enrico_ws/reconstructionEvaluator/config/kitti06_mono.config >> stdout &
cd ~/enrico_ws/reconstructionEvaluator/output/KITTI/07_mono && ~/enrico_ws/reconstructionEvaluator/reconstructionEvaluator ~/enrico_ws/reconstructionEvaluator/config/kitti07_mono.config >> stdout &
cd ~/enrico_ws/reconstructionEvaluator/output/KITTI/08_mono && ~/enrico_ws/reconstructionEvaluator/reconstructionEvaluator ~/enrico_ws/reconstructionEvaluator/config/kitti08_mono.config >> stdout &
cd ~/enrico_ws/reconstructionEvaluator/output/KITTI/09_mono && ~/enrico_ws/reconstructionEvaluator/reconstructionEvaluator ~/enrico_ws/reconstructionEvaluator/config/kitti09_mono.config >> stdout &
cd ~/enrico_ws/reconstructionEvaluator/output/KITTI/10_mono && ~/enrico_ws/reconstructionEvaluator/reconstructionEvaluator ~/enrico_ws/reconstructionEvaluator/config/kitti10_mono.config >> stdout &
